// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdxwyecwdpyhaunvukaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpkeHd5ZWN3ZHB5aGF1bnZ1a2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDI5MzcsImV4cCI6MjA1ODQ3ODkzN30.Ssz4HcbYKwSqswsPqzvKkCZdvvNUEH-nEAvwzmc4Jas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);